---
- name: Debug current host
  debug:
    msg: "Running on {{ inventory_hostname }}"

- name: List files in home directory
  command: ls -la /home/azureuser
  register: ls_output

- name: Show the output of 'ls'
  debug:
   var: ls_output.stdout

- name: Install prerequisite packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: true

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install Docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add azureuser to the docker group
  user:
    name: azureuser
    groups: docker
    append: yes
