---

    - name: Add HashiCorp GPG Key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600

    - name: Install Vault
      apt:
        name: vault
        state: present

    - name: Create Vault configuration directory
      file:
        path: /etc/vault.d
        state: directory
        mode: '0755'

    - name: Create Vault data directory
      file:
        path: /opt/vault/data
        state: directory
        mode: '0755'

    - name: Install Vault configuration file
      template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        mode: '0644'
    - name: Display instructions for starting Vault manually
      debug:
        msg: "Vault installation is complete. Please start Vault manually with the command: 'vault server -config=/etc/vault.d/vault.hcl'"

    # # Démarrage manuel de Vault avec nohup
    # - name: Start Vault in background using nohup
    #   shell: "nohup vault server -config=/etc/vault.d/vault.hcl > /var/log/vault.log 2>&1 &"
    #   args:
    #     executable: /bin/bash

    # - name: Wait for Vault to start
    #   pause:
    #     seconds: 5

    # - name: Check Vault status
    #   command: vault status
    #   register: vault_status

    # - name: Display Vault status
    #   debug:
    #     msg: "{{ vault_status.stdout }}"
